version: "3"
services:
  mysql-light:
    image: mysql
    container_name: mysql-light
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      TZ: "Europe/Paris"
    restart: always
    networks:
      - strapi-mysql-network-light

  phpmyadmin-light:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-mysql-light
    networks:
      - strapi-mysql-network-light
    environment:
      PMA_HOST: mysql-light
      PMA_PORT: ${DATABASE_PORT}
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    depends_on:
      - mysql-light

networks:
  strapi-mysql-network-light:
    driver: bridge

volumes:
  db_data:
